### PR TITLE
Add flushKey command

### PR DESCRIPTION
**Pull request by alevy**
The `flushKey` command is just a flush command with a key associated with it.

/cc @saschat

### CODE REVIEW

**Comment by dterei** [comment]
Mmm, this is only useful specifically for memcachier, I'd rather not pollute the public interface just for this.

We should either just fork `memcache-hs` or expose enough through probably a `.Internal` module for a library user to write `flushKey` themselves.

**Comment by saschat** [comment]
How about we add a `ReqRaw Word8 (Maybe Key) (Maybe Value) Builder Int` constructor to `OpRequest`? Then
```
szOpRequest (ReqRaw op mKey mValue b i) = (op, mKey, mValue, b, i)
```
and the flush command with a key would than be `ReqRaw 0x08 (Just "keyname") Nothing  mempty 0`.

**Comment by dterei** [comment]
Yep, that's indeed what I've done.

An external client can now implement `flushKey` as follows:

```
import Blaze.ByteString.Builder
#if __GLASGOW_HASKELL__ < 710
import Control.Applicative
#endif
import Control.Exception (throwIO)
import Control.Monad (forM_, when)

import Database.Memcache.Cluster
import Database.Memcache.Errors
import Database.Memcache.Types

-- | Remove (delete) all currently stored key-value pairs from the cluster. The
-- expiration value can be used to cause this flush to occur in the future
-- rather than immediately.
flushKey :: Cluster -> Key -> Maybe Expiration -> IO ()
flushKey c key e = do
    let extras = szExtra e
        msg = emptyReq { reqOp = ReqRaw 0x08 (Just key) Nothing extras }
    results <- allOp c msg
    forM_ results $ \(_, r) -> do
        when (resOp r /= ResFlush Loud) $ throwIO $ wrongOp r "FLUSH"
        case resStatus r of
            NoError -> return ()
            rs      -> throwStatus rs

  where
    szExtra (Just e') = SERaw (fromWord32be e') 4
    szExtra Nothing   = SERaw mempty 0
```

**Comment by dterei** [comment]
You'll need to use the just released version:

http://hackage.haskell.org/package/memcache-0.2.0.1

**Pull request closed without merging**
