### PR TITLE
Fixes #6 

### LINKED ISSUE #6: `NotEnoughBytes` with payloads bigger than 1420 bytes
GHC Version: 7.10.2
Platform: Mac OS X El Capitan 10.11.3

Hey @dterei !

First of all thank you for this library, it's one of the best out there when it comes to memcached (kudos for implementing authentication, it's the first thing other projects miss!). At work, I have been trying to use this library to talk to memcachier to provide us with a simple key/value cache, but I'm hitting a strange behaviour I will do my best in trying to explain here.

I have some run-of-the-mill code to provide a cache interface, which is not important, but that I'm reporting here for completeness:

``` haskell
memcacheLookup :: (IsKey k, IsValue v) => RemoteCacheProvider Memcache -> k -> IO (Maybe v)
memcacheLookup (MemcacheProvider client) k = do
  res <- Memcache.get client (toS $ toKey k)
  case res of
    Nothing -> return Nothing
    Just (val, _, _) -> return . JSON.decode . toS $ val

memcacheStore :: (IsKey k, IsValue v) => RemoteCacheProvider Memcache -> k -> v -> IO ()
memcacheStore (MemcacheProvider client) k v = do
  let key     = toS $ toKey k
  let payload = toS . JSON.encode $ v
  res <- Memcache.get client key
  case res of
    Nothing -> void $ Memcache.set client key payload 0 0
    Just (_, _, cas) -> void $ Memcache.set' client key payload 0 0 cas

memcacheDelete :: (IsKey k, IsValue v) => RemoteCacheProvider Memcache -> k -> IO (Proxy v)
memcacheDelete (MemcacheProvider client) k = do
  void $ Memcache.delete client (toS $ toKey k) 0
  return Proxy
```

As you can see, we are serialising/deserialising back and forth some JSON, but this is irrelevant. I have then written a spec which triggers a surprising problem:

``` haskell
newtype TestPayload = TP { value :: T.Text } deriving (Show, Eq)

deriveJSON defaultOptions ''TestPayload

memcacheCacheSpecs :: AppEnv -> Spec
memcacheCacheSpecs e = beforeAll wipeCache $ do
  let cache = e ^. appCache
  describe "Memcache Cache & Caching" $ do
    it "Storing and looking up stuff yield (Just x)" $ do
      let v = TP (T.replicate 2123 "a")
      putStrLn $ "====> SIZE: " <> show (B.length $ toS (JSON.encode v))
      cacheStore cache (CK $ UserID 50) v
      (r :: Maybe TestPayload) <- cacheLookup cache (CK $ UserID 50)
      r `shouldBe` Just v
  where
    wipeCache = do
      (_ :: Proxy TestPayload) <- cacheDelete (e ^. appCache) (CK $ UserID 50)
      return ()
```

As you can see, I'm simplifying everything at maximum, which is essentially sending over the wire a simple json filled with all `a` s, something like:

```
{ "value": "aaaaaaaaaaa" }
```

The error being thrown by your library, if I try to `cacheLookup` this value after a `cacheStore`, is `NotEnoughBytes`. I have dug deeper into the internals and indeed such error is thrown here, when the library receives less than the expected amount of bytes from the socket:

https://github.com/dterei/memcache-hs/blob/master/Database/Memcache/Wire.hs#L44

I have forked the library and added a bunch of `putStrLn` statements, like this:

``` haskell
recv :: Socket -> IO Response
recv s = do
    header <- recvAll mEMCACHE_HEADER_SIZE
    let h = dzHeader' (L.fromChunks [header])
    if bodyLen h > 0
        then do
          putStrLn $ "==> BodyLen: " <> show (bodyLen h)
          let bytesToRead = fromIntegral $ bodyLen h
          putStrLn $ "==> BytesToRead: " <> show bytesToRead
          body <- recvAll bytesToRead
          return $ dzBody' h (L.fromChunks [body])
        else return $ dzBody' h L.empty
  where
    recvAll :: Int -> IO B.ByteString
    recvAll n = do
        putStrLn $ "==> Going to read " <> show n <> " bytes..."
        buf <- N.recv s n
        let bufLen = B.length buf
        putStrLn $ "==> I have read " <> show bufLen <> " bytes..."
        if bufLen == n
          then return buf
          else throwIO NotEnoughBytes
``` 

And, armed with this tools, I have rerun the specs:

screen shot 2016-02-25 at 12 51 47

As you can see, there is this magical `1424` bytes value which is the maximum value we get back from the socket. If I try to pass a smaller payload, which size is smaller or equal than 1424, it works correctly. I have found this empirical number which is **1420**: if my payload is bigger than 1420 bytes, the library will try to read more than `1424` bytes (Apparently there are 4 extra bytes at the end coming out of nowhere -- padding perhaps?) and everything breaks.

I have tried to perform a get on large payload with a Python client, to try to rule out as many problems as possible, and the latter works correctly:

screen shot 2016-02-25 at 12 31 39

It's also using the same memcachier instance, which rules out some weird memcachier config issue.

I think that, from my perspective, we are faced with one of these three:

1. There is a bug in my understanding of this API and/or in my `store/lookup/delete` functions

2. There is a bug in this library

3. There is a very sneaky bug in the `network` package, specifically in the `recv` function for `ByteString`s.

What do you think? Any input from you would be highly appreciated and value? Please shout if you need any reproduction steps. 

Thanks a ton!

Alfredo

### PR DESCRIPTION
**Pull request by adinapoli**
Hey @dterei ,

as promised here comes my PR. I have test it with a bunch of different scenarios (I have specs which generates `QuickChecked`d, `Arbitrary` payloads) and it seems to work just fine.

The core of the solution is to make `recvAll` tail recursive by carrying around a `Builder` which incrementally read the packets from the Socket. The strictness annotations are there only to force in WHNF the strict necessary (no pun intended!) and avoid building unnecessary thunks during the recursion.

Certainly smarter/faster algorithm could be developed but I think this is a good start.

Could I kindly ask you to:

* Review this PR and tell me if I'm doing anything utterly silly
* If all is :+1: , merge this and release an updated version on Hackage
* If you think my contribution was worthwhile, consider adding me as a contributor in the `README` file.

Thanks!

Alfredo

### CODE REVIEW

**Comment by dterei** [comment]
Looks great! Thanks for fixing the bug! I'll add you as a contributor and do a new release.

**Comment by adinapoli** [comment]
Thank you David!

Have a nice weekend!

Alfredo

**Comment by dterei** [comment]
Alfredo, the tests that you wrote for this, would they make sense to push upstream?

**Comment by adinapoli** [comment]
Hey David,

They are quite business agnostic so yes, I can cook up something. I'm from
mobile right now, but I have been competitor libraries using QC to write a
bunch of properties to test the internals of the lib, so we could
definitely predate something!

**Comment by dterei** [comment]
OK, Hackage updated to `v0.1.0.1`. Thanks!

**Comment by adinapoli** [comment]
:tada:

**Pull request merged**
